using PropDesk.Domain.Models;

namespace PropDesk.Reporting;

/// <summary>
/// Generates PDF reports using plain HTML → PDF via WebView2 or iText7.
/// For now produces a formatted HTML file as intermediate step.
/// Install: dotnet add package itext7
/// </summary>
public class PdfReportService
{
    public void ExportPayoutHistory(string outputPath, List<PayoutCycle> cycles, decimal totalPaid)
    {
        // Generate clean HTML report
        var html = BuildPayoutHtml(cycles, totalPaid);
        var htmlPath = outputPath.Replace(".pdf", "_report.html");
        File.WriteAllText(htmlPath, html);

        // TODO: convert to PDF with iText7 or WebView2 print
        // For now, the HTML file is the deliverable (fully formatted, printable)
        // iText7 integration:
        // using iText.Html2pdf;
        // HtmlConverter.ConvertToPdf(html, new FileStream(outputPath, FileMode.Create));
    }

    public void ExportDashboardReport(string outputPath, DashboardReportData data)
    {
        var html = BuildDashboardHtml(data);
        File.WriteAllText(outputPath, html);
    }

    private string BuildPayoutHtml(List<PayoutCycle> cycles, decimal totalPaid) => $"""
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8"/>
          <title>PropDesk – Payout History Report</title>
          <style>
            body {{ font-family: Arial, sans-serif; background: #1E1E2E; color: #F8F8F2; margin: 40px; }}
            h1   {{ color: #50FA7B; font-size: 26px; border-bottom: 2px solid #44475A; padding-bottom: 10px; }}
            h2   {{ color: #4C9BE8; font-size: 16px; margin-top: 30px; }}
            .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
            .card {{ background: #2A2A3E; border-radius: 8px; padding: 16px 24px; flex: 1; }}
            .card .label {{ font-size: 11px; color: #6272A4; }}
            .card .value {{ font-size: 24px; font-weight: bold; color: #F8F8F2; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
            th {{ background: #12121E; color: #4C9BE8; padding: 10px; text-align: left; font-size: 12px; }}
            td {{ padding: 10px; border-bottom: 1px solid #3A3A5C; font-size: 12px; }}
            tr:nth-child(even) {{ background: #252535; }}
            .paid   {{ color: #50FA7B; font-weight: bold; }}
            .active {{ color: #F1FA8C; font-weight: bold; }}
            .footer {{ margin-top: 40px; font-size: 10px; color: #6272A4; text-align: center; }}
          </style>
        </head>
        <body>
          <h1>⚡ PropDesk – Payout History Report</h1>
          <p style="color:#6272A4">Generated: {DateTime.Now:MMMM dd, yyyy HH:mm}</p>

          <div class="summary">
            <div class="card">
              <div class="label">Total Cycles</div>
              <div class="value">{cycles.Count}</div>
            </div>
            <div class="card">
              <div class="label">Total Paid Out</div>
              <div class="value" style="color:#50FA7B">${totalPaid:N2}</div>
            </div>
            <div class="card">
              <div class="label">Average Per Cycle</div>
              <div class="value" style="color:#4C9BE8">${(cycles.Count > 0 ? totalPaid / cycles.Count : 0):N2}</div>
            </div>
            <div class="card">
              <div class="label">Best Cycle</div>
              <div class="value" style="color:#F1FA8C">${(cycles.Any() ? cycles.Max(c => c.AmountPaid) : 0):N2}</div>
            </div>
          </div>

          <h2>📋 Cycle Detail</h2>
          <table>
            <tr>
              <th>#</th><th>Start</th><th>End</th><th>Net Profit</th>
              <th>Largest Day</th><th>Consistency</th><th>Paid Out</th><th>Status</th>
            </tr>
            {string.Join("\n", cycles.Select((c, i) => $"""
              <tr>
                <td>{i + 1}</td>
                <td>{c.StartDate:MM/dd/yyyy}</td>
                <td>{c.EndDate?.ToString("MM/dd/yyyy") ?? "Active"}</td>
                <td>${c.NetProfit:N2}</td>
                <td>${c.LargestWinDay:N2}</td>
                <td>{c.ConsistencyPercent:N2}%</td>
                <td class="{(c.Status == "Paid" ? "paid" : "active")}">${c.AmountPaid:N2}</td>
                <td class="{(c.Status == "Paid" ? "paid" : "active")}">{c.Status}</td>
              </tr>
            """))}
          </table>

          <div class="footer">PropDesk v1.0 | Generated by PropDesk Analytics Platform</div>
        </body>
        </html>
        """;

    private string BuildDashboardHtml(DashboardReportData d) => $"""
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8"/>
          <title>PropDesk – Performance Report</title>
          <style>
            body {{ font-family: Arial, sans-serif; background: #1E1E2E; color: #F8F8F2; margin: 40px; }}
            h1   {{ color: #4C9BE8; font-size: 24px; }}
            .grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin: 20px 0; }}
            .card {{ background: #2A2A3E; border-radius: 8px; padding: 16px; }}
            .label {{ font-size: 10px; color: #6272A4; margin-bottom: 4px; }}
            .value {{ font-size: 20px; font-weight: bold; }}
            .green {{ color: #50FA7B; }} .red {{ color: #FF5555; }} .yellow {{ color: #F1FA8C; }} .blue {{ color: #4C9BE8; }}
          </style>
        </head>
        <body>
          <h1>⚡ PropDesk – Performance Report</h1>
          <p style="color:#6272A4">Generated: {DateTime.Now:MMMM dd, yyyy} | Account: {d.AccountName}</p>
          <div class="grid">
            <div class="card"><div class="label">Net Profit</div><div class="value green">${d.NetProfit:N2}</div></div>
            <div class="card"><div class="label">Consistency</div><div class="value {(d.ConsistencyPct < 50 ? "green" : "red")}">{d.ConsistencyPct:N2}%</div></div>
            <div class="card"><div class="label">Eligibility</div><div class="value {(d.IsEligible ? "green" : "red")}">{(d.IsEligible ? "✅ ELIGIBLE" : "❌ NOT YET")}</div></div>
            <div class="card"><div class="label">Largest Win Day</div><div class="value yellow">${d.LargestWinDay:N2}</div></div>
            <div class="card"><div class="label">Buffer</div><div class="value blue">${d.Buffer:N2}</div></div>
            <div class="card"><div class="label">Trading Days</div><div class="value">{d.TradingDays} / {d.MinDays}</div></div>
          </div>
        </body>
        </html>
        """;
}

public record DashboardReportData(
    string  AccountName,
    decimal NetProfit,
    decimal ConsistencyPct,
    decimal LargestWinDay,
    decimal Buffer,
    int     TradingDays,
    int     MinDays,
    bool    IsEligible
);